version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/carlpett/grafana-loader
    steps:
      - checkout
      - run: make build
      - store_artifacts:
          path: grafana-loader
          destination: grafana-loader
  release:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/carlpett/grafana-loader
    steps:
      - checkout
      - run: make release

workflows:
  version: 2
  github:
    jobs:
      - build
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
